version: "3.8"

services:
  serverjson:
    image: banghasan/serverjson:main
    container_name: serverjson
    ports:
      - "8000:8000"
    environment:
      - AUTH_HEADER=r4HaS1AbangHaSAN
    volumes:
      - ./data:/app/data
    restart: unless-stopped
